version: "3.8"

services:
  mimictalk:
    # 替换为你导出/打包的镜像名:标签
    image: my-mimictalk:v1.0
    container_name: mimictalk  # 容器名仍为mimictalk，生效不变
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./checkpoints_mimictalk:/app/checkpoints_mimictalk
      - ./data:/app/data
      - ./infer_outs:/app/infer_outs
    shm_size: '8gb'

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app

    ports:
      - "7860:7860"
    stdin_open: true
    tty: true